server:
  port: 80
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://hoho.com:7001/eureka,http://yoyo.com:7002/eureka

